name: "flake test"
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Check out repository
      uses: actions/checkout@v2.4.0

    - name: Install Nix
      uses: cachix/install-nix-action@v16

    - name: Build dev environment
      run: nix develop
